version: '1.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - TZ=Asia/Seoul
      - cluster.name=mincheol-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network    
    command: >
          bash -c '
          if [ ! -d plugins/analysis-nori ]; then
            elasticsearch-plugin install analysis-nori;
          fi &&
          exec elasticsearch'


  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Seoul
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge

volumes:
  elastic-data:
    driver: local
    